[workspace]
members = ["nam-core", "nam-cli", "nam-plugin", "nam-trainer", "xtask"]
exclude = ["fuzz", "third-party/nih-plug"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
rust-version = "1.88"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
expect_used = "deny"
print_stderr = "deny"
print_stdout = "deny"
todo = "deny"
undocumented_unsafe_blocks = "deny"
unwrap_used = "deny"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[patch.crates-io]
block = { path = "third-party/block-0.1.6" }
proc-macro-error2 = { path = "third-party/proc-macro-error2-2.0.1" }
